// Collection Names
export const CLUBS_INFORMATION_COLLECTION_NAME = "CLUBS-DETAILS-INFORMATION";
export const EVENTS_INFORMATION_COLLECTION_NAME = "EVENTS-DETAILS-INFORMATION";
export const SUB_EVENTS_INFORMATION_COLLECTION_NAME = "SUB-EVENTS-DETAILS-INFORMATION";
export const ADMINS_INFORMATION_COLLECTION_NAME = "ADMINS-DETAILS-INFORMATION";
export const SUB_ADMINS_INFORMATION_COLLECTION_NAME = "SUB-ADMINS-DETAILS-INFORMATION";
